#!/bin/bash

echo "🔧 Configurando GitHub Pages..."

echo ""
echo "📋 Pasos para configurar GitHub Pages:"
echo ""
echo "1. Ve a: https://github.com/benjamalegni/financialfeeling/settings/pages"
echo ""
echo "2. En la sección 'Source', selecciona:"
echo "   ✅ Deploy from a branch"
echo ""
echo "3. En 'Branch', selecciona:"
echo "   ✅ gh-pages"
echo ""
echo "4. En 'Folder', deja:"
echo "   ✅ / (root)"
echo ""
echo "5. Click 'Save'"
echo ""
echo "6. Espera unos minutos para que se active"
echo ""
echo "🌐 Tu sitio estará disponible en:"
echo "   https://benjamalegni.github.io/financialfeeling/"
echo ""
echo "✅ ¡Deploy completado exitosamente!"
echo "📦 Build: ✅"
echo "📤 Push a gh-pages: ✅"
echo "🔧 Configuración manual necesaria: ✅" 